# Generated by Django 2.2.9 on 2020-01-26 19:18

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_img',
            field=models.FileField(default='a.jpg', upload_to=users.models.get_attachment_path, verbose_name='Profile image'),
            preserve_default=False,
        ),
    ]
