# Generated by Django 2.2.9 on 2020-01-19 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='Project name')),
                ('slug', models.SlugField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('task', 'Task'), ('bug', 'Bug')], default='task', max_length=5, verbose_name='Issue type')),
                ('issue_status', models.CharField(choices=[('to do', 'To do'), ('in progress', 'In progress'), ('done', 'done')], default='to do', max_length=20, verbose_name='Issue status')),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=10, verbose_name='Issue priority')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('summary', models.TextField(verbose_name='Podsumowanie')),
                ('description', models.TextField(verbose_name='Description')),
                ('environment', models.TextField(verbose_name='Environment')),
                ('assingee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues_assignee', to=settings.AUTH_USER_MODEL, verbose_name='Assignee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='issues.Project', verbose_name='Project')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues_reporter', to=settings.AUTH_USER_MODEL, verbose_name='Reporter')),
            ],
        ),
    ]
