# Generated by Django 2.2.9 on 2020-01-26 19:03

from django.db import migrations, models
import issues.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=issues.models.get_attachment_path, verbose_name='File')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Added')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(verbose_name='Comment')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('task', 'Task'), ('bug', 'Bug')], default='task', max_length=5, verbose_name='Issue type')),
                ('issue_status', models.CharField(choices=[('to do', 'To do'), ('in progress', 'In progress'), ('done', 'done')], default='to do', max_length=20, verbose_name='Issue status')),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=10, verbose_name='Issue priority')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('summary', models.TextField(max_length=250, verbose_name='Summary')),
                ('description', models.TextField(verbose_name='Description')),
                ('environment', models.CharField(choices=[('local', 'Local'), ('dev', 'Development'), ('test', 'Test'), ('stage', 'Stage'), ('prod', 'Production')], default='local', max_length=100, verbose_name='Environment')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='Project name')),
                ('slug', models.SlugField(max_length=10)),
            ],
        ),
    ]
