# Generated by Django 2.2.9 on 2020-01-19 18:43

from django.db import migrations, models
import django.db.models.deletion
import issues.models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_auto_20200119_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=issues.models.get_attachment_path, verbose_name='File')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Added')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='issues.Issue', verbose_name='Issue')),
            ],
        ),
    ]
