# Generated by Django 3.0.2 on 2020-02-02 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_auto_20200126_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('in progress', 'In progress'), ('success', 'success'), ('cancel', 'cancel')], default='in progress', max_length=20, verbose_name='Project status'),
        ),
    ]
