# Generated by Django 3.0.2 on 2020-02-02 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_auto_20200202_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_status',
            new_name='status',
        ),
    ]
