# Generated by Django 2.2.9 on 2020-01-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_auto_20200120_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='environment',
            field=models.CharField(choices=[('local', 'Local'), ('dev', 'Development'), ('test', 'Test'), ('stage', 'Stage'), ('prod', 'Production')], default='local', max_length=100, verbose_name='Environment'),
        ),
    ]
