# Generated by Django 3.0.2 on 2020-02-04 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_auto_20200202_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='assingee',
            new_name='assignee',
        ),
    ]
