# Generated by Django 3.0.2 on 2020-02-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_auto_20200204_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_status',
            field=models.CharField(choices=[('to do', 'To do'), ('in progress', 'In progress'), ('done', 'done'), ('cancel', 'cancel')], default='to do', max_length=20, verbose_name='Issue status'),
        ),
    ]
