# Generated by Django 3.0.2 on 2020-02-05 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0007_auto_20200205_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='issue_status',
            new_name='status',
        ),
    ]
