# Generated by Django 3.0.2 on 2020-02-05 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0008_auto_20200205_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='issue_type',
            new_name='type',
        ),
    ]
