# Generated by Django 3.0.2 on 2020-02-06 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0009_auto_20200205_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_text',
            new_name='text',
        ),
    ]
