# Generated by Django 3.0.2 on 2020-02-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0010_auto_20200206_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='summary',
            field=models.TextField(max_length=50, verbose_name='Summary'),
        ),
    ]
