# Generated by Django 3.0.2 on 2020-02-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0011_auto_20200206_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='environment',
            field=models.CharField(blank=True, choices=[('local', 'Local'), ('dev', 'Development'), ('test', 'Test'), ('stage', 'Stage'), ('prod', 'Production')], max_length=100, verbose_name='Environment'),
        ),
    ]
