# Generated by Django 3.0.2 on 2020-02-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0012_auto_20200209_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('to do', 'To do'), ('in progress', 'In progress'), ('done', 'Done'), ('cancel', 'Cancel')], default='to do', max_length=20, verbose_name='Issue status'),
        ),
    ]
